server:
  port: 8083

spring:
  application:
    name: demo-springcloud3-eureka

eureka:
  instance:
    hostname: eureka3 #注册中心IP地址
  client:
    register-with-eureka: false  #是否向注册中心注册自己，默认 true
    fetch-registry: false #检索其他服务
    service-url: #服务注册中心配置，，指定注册中心位置
      defaultZone: http://localhost:8081, http://eureka2:8082
