server:
  port: 8081

spring:
  application:
    name: demo-springcloud1-eureka

eureka:
  instance:
    hostname: eureka1 #注册中心IP地址
  client:
    register-with-eureka: false  #是否向注册中心注册自己，默认 true
    fetch-registry: false
    service-url: #服务注册中心配置，，指定注册中心位置
      defaultZone: http://eureka2:8082, http://127.0.0.1:8083
